backend:
  name: git-gateway
  #repo: nanandann/pcloudy-docs   # your GitHub repo
  branch: main
  #base_url: https://api.netlify.com
  #auth_endpoint: auth?provider=github&scope=repo&site_id=1c39c10d-d3a5-4e68-815b-2cb0517a66e2       # your main branch

media_folder: static/img
public_folder: /img

collections:
  - name: docs
    label: Documentation
    folder: docs
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
